[build]
  publish = "frontend"

[[redirects]]
  from = "/quickaccess/membership.html"
  to = "/quickaccess/membership.html"
  status = 200

[[redirects]]
  from = "/quickaccess/wallet.html"
  to = "/quickaccess/wallet.html"
  status = 200

[[redirects]]
  from = "/quickaccess/history.html"
  to = "/quickaccess/history.html"
  status = 200

[[redirects]]
  from = "/quickaccess/locationpref.html"
  to = "/quickaccess/locationpref.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200